#!/usr/bin/env python3
import yaml
import rospy
from joint_state_recorder_panda import JointStatesRecorderPanda
import rospkg
import os
import argparse


if __name__ == "__main__":
    argument_parser = argparse.ArgumentParser(description='Run the parameter optimizer')
    argument_parser.add_argument("--joint-state-topic-name", "-j", help="Topic where the joint state is published")
    argument_parser.add_argument("--robot-name", "-r", help="name of the robot that you are calibrating, e.g. panda_4")
    argument_parser.add_argument("--tool-position-on-table", "-t", help="postion of the tool on the table for the franka")
    argument_parser.add_argument("--config-file", "-c", help="config file with the ip, admin and password of the robots")



    args = argument_parser.parse_args()
    joint_state_topic_name = args.joint_state_topic_name
    robot_name = args.robot_name
    config_file = args.config_file
    tool_position = args.tool_position_on_table
    package=os.path.join(rospkg.RosPack().get_path('calibration_tools'))
    data_folder =  os.path.abspath(os.path.join(package, os.pardir, os.pardir, os.pardir, 'data', robot_name, tool_position)) 
    print(data_folder)
    print("Joint_state", joint_state_topic_name)
    print("Robot name:",robot_name)
    config_path = os.path.join(package, 'config', config_file)
    print("Config file:",config_path)
    config = yaml.load(open(config_path, 'r'), Loader=yaml.FullLoader)
    node = JointStatesRecorderPanda(joint_state_topic_name, data_folder, config)
    try:
        node.run()
    except rospy.ROSInterruptException:
        pass

